services:
  - type: web
    name: wonder-lust
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: NODE_ENV
        value: production
      - key: ATLASDB_URL
        sync: false
      - key: SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: GEOAPIFY_API_KEY
        sync: false
